export const contactTable = [
    {
        contactId: '0',
        firstName: 'John',
        lastName: 'Doe',
        position: 'Developer',
        businessEmail: 'jon_doe@gmail.com',
        personalEmail: 'john_doe_companymail@gmail.com',
        businessPhone: '800-835-3746',
        mobilePhone: '09807352472',
        skype: 'John Doe',
        whatsApp: 'John Doe',
        homeAddress: 'District 2 1657 Riverside Drive Redding 530-225-3426',
        note: 'none',
        isActive: '1',
        createdBy: 'Kim Villarojo',
        Admin: 'Admin',
        company: 'XYZ Company',
        leadStatus: 'None',
        leadSource: 'Google',
        dateCreated: '09/07/2019',
        dateUpdated: '09/07/2019',
    },
    {
        contactId: '1',
        firstName: 'Ryan Jade',
        LastName: 'Foo',
        position: 'Call Center Agent',
        businessEmail: 'ryan_jade@gmail.com',
        personalEmail: 'ryan_jade_companymail@gmail.com',
        businessPhone: '202-555-0189',
        mobilePhone: '09807352472',
        skype: 'Ryan Foo',
        whatsApp: 'Ryan Foo',
        homeAddress: 'District 1 1656 Union Street Eureka 707-445-6600',
        note: 'Not Sure',
        IsActive: '1',
        createdBy: 'Kim Villarojo',
        Admin: 'Admin',
        company: 'Google',
        leadStatus: 'Attempted Contact',
        leadSource: 'Linked In',
        dateCreated: '09/07/2019',
        dateUpdated: '09/07/2019',
    },
    {
        contactId: '2',
        firstName: 'Jonny',
        LastName: 'Bravo',
        position: 'Call Center Admin',
        businessEmail: 'jonny_bra@gmail.com',
        personalEmail: 'jonny_bra_companymail@gmail.com',
        businessPhone: '202-555-0166',
        mobilePhone: '09079374932',
        skype: 'Jonny Bra',
        whatsApp: 'Jonny Bra',
        homeAddress: 'DHeadquarters 1120 N Street Sacramento 916-654-5266',
        note: '',
        IsActive: '1',
        createdBy: 'Kim Villarojo',
        Admin: 'Admin',
        company: 'ASUS',
        leadStatus: 'Junked Lead',
        leadSource: 'Zoom Info',
        dateCreated: '09/07/2019',
        dateUpdated: '09/07/2019',
    }
]

export const companyTable = {

}