export const API_CALL_REQUEST = "API_CALL_REQUEST";
export const API_CALL_SUCCESS = "API_CALL_SUCCESS";
export const API_CALL_FAILURE = "API_CALL_FAILURE";

// Login constants
export const API_LOGIN_REQUEST = 'API_LOGIN_REQUEST';
export const API_LOGIN_SUCCESS = 'API_LOGIN_SUCCESS';
export const API_LOGIN_ERROR = 'API_LOGIN_ERROR';
export const API_LOGIN_CREDENTIAL = 'API_LOGIN_CREDENTIAL';

// register constants
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_REQUEST_SUCCESS = 'REGISTER_REQUEST_SUCCESS';
export const REGISTER_REQUEST_FAILED = 'REGISTER_REQUEST_FAILED';
export const REGISTER_REQUEST_DETAILES = 'REGISTER_REQUEST_DETAILES';

// Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCESS = 'LOGOUT_REQUEST_SUCCESS';
export const LOGOUT_REQUEST_ERROR = 'LOGOUT_REQUEST_ERROR';

// Intities  ( Company , Projects, Contacts )
export const GET_ENTITY_REQUEST = 'GET_ENTITY_REQUEST';
export const GET_ENTITY_REQUEST_SUCCESS = 'GET_ENTITY_REQUEST_SUCCESSs';
export const GET_ENTITY_REQUEST_FAILED = 'GET_ENTITY_REQUEST_FAILED';
export const GET_ENTITY_REQUEST_ERROR = 'GET_ENTITY_REQUEST_ERROR';


// export const GET_ENTITY_BY_ID_REQUEST = 'GET_ENTITY_BY_ID_REQUEST';
// export const GET_ENTITY_BY_ID__REQUEST_SUCCESS = 'GET_ENTITY_BY_ID__REQUEST_SUCCESS';
// export const GET_ENTITY_BY_ID__REQUEST_FAILED = 'GET_ENTITY_BY_ID__REQUEST_FAILED';

export const REMOVE_ENTITY_REQUEST = 'REMOVE_ENTITY_REQUEST';
export const REMOVE_ENTITY_REQUEST_SUCCESS = 'REMOVE_ENTITY_REQUEST_SUCCESS';
export const REMOVE_ENTITY_REQUEST_FAILED = 'REMOVE_ENTITY_REQUEST_FAILED'; 

export const UPDATE_ENTITY_REQUEST = 'UPDATE_ENTITY_REQUEST';
export const UPDATE_ENTITY_REQUEST_SUCCESS = 'UPDATE_ENTITY_REQUEST_SUCCESS';
export const UPDATE_ENTITY_REQUEST_FAILED = 'UPDATE_ENTITY_REQUEST_FAILED'; 

export const GET_NAME_LIST_REQUEST = 'GET_NAME_LIST_REQUEST';
export const GET_NAME_LIST_REQUEST_SUCCESS = 'GET_NAME_LIST_REQUEST_SUCCESS';
export const GET_NAME_LIST_REQUEST_FAILED = 'GET_NAME_LIST_REQUEST_FAILED'; 

export const ADD_CONTACT_REQUEST = 'ADD_COTACT_REQUEST';
export const ADD_CONTACT_REQUEST_SUCCESS = 'ADD_CONTACT_REQUEST_SUCCESS';
export const ADD_CONTACT_REQUEST_FAILED = 'ADD_CONTACT_REQUEST_FAILED'; 

// register constants
export const COMPANY_REQUESTED = 'COMPANY_REQUESTED';
export const COMPANY_REQUEST_SUCCESS = 'COMPANY_REQUEST_SUCCESS';
export const COMPANY_REQUEST_FAILED = 'COMPANY_REQUEST_FAILED';
export const COMPANY_REQUEST_ERROR = 'COMPANY_REQUEST_DETAILES';

// Root constans
export const API_USER_LOCALSTORAGE_REQUEST = 'API_USER_LOCALSTORAGE';
export const API_USER_LOCALSTORAGE_SUCCESS = 'API_USER_LOCALSTORAGE_SUCCESS';
export const API_USER_LOCALSTORAGE_ERROR = 'API_USER_LOCALSTORAGE_ERROR';